# Create a Tensor

In [1]:
import torch

In [2]:
a = torch.empty(1)
a

tensor([-226.8628])

In [3]:
b = torch.empty(2)
b

tensor([1.8543e+14, 3.0618e-41])

In [4]:
b.shape

torch.Size([2])

In [5]:
c = torch.empty(3,4)
c

tensor([[ 5.8083e+13,  3.0618e-41, -3.3582e+00,  4.4891e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [6]:
c.ndimension()

2

In [7]:
d = torch.empty(3 , 4 , 6)
d

tensor([[[ 5.6052e-45,  0.0000e+00, -1.7014e+38,  1.1515e-40,  1.1210e-43,
           0.0000e+00],
         [ 4.4842e-44,  0.0000e+00,  1.2962e-37,  3.0625e-41,  0.0000e+00,
           1.4013e-45],
         [ 0.0000e+00,  0.0000e+00,  4.2740e-43,  0.0000e+00, -2.2686e+02,
           4.4891e-41],
         [ 3.2753e+14,  3.0618e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00]],

        [[ 0.0000e+00,  3.0625e-41,  1.8788e+31,  1.7220e+22,  2.1715e-18,
           2.1628e+23],
         [ 6.5993e-10,  4.2007e-05,  6.6285e-10,  1.0693e-05,  2.6286e-06,
           1.0561e-05],
         [ 2.6880e-06,  6.5619e-10,  2.4152e-18,  3.1360e+27,  7.0800e+31,
           3.1095e-18],
         [ 4.7851e+22,  2.8826e+32,  4.4248e+30,  7.6729e+34,  2.1707e-18,
           4.5447e+30]],

        [[ 7.0062e+22,  2.1715e-18,  4.5447e+30,  7.0062e+22,  2.1707e-18,
           1.9284e+31],
         [ 3.2314e-18,  3.7748e-08,  1.3400e-08,  1.0016e-11,  2.7446e-06,
           5.2009e+22],
      

In [8]:
d.dtype

torch.float32

In [9]:
type(d)

torch.Tensor

In [10]:
e = torch.ones(2 , 3)
e

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
f = torch.zeros(2 , 3 , 5)
f

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [12]:
g = torch.rand(1, 3 )
g

tensor([[0.7832, 0.6724, 0.9381]])

In [13]:
g.shape

torch.Size([1, 3])

In [14]:
g.size()

torch.Size([1, 3])

In [15]:
h = torch.rand(3 , 4 , 4)
h

tensor([[[0.6847, 0.6055, 0.0867, 0.0591],
         [0.6079, 0.3703, 0.7900, 0.0634],
         [0.4806, 0.5565, 0.2181, 0.3187],
         [0.7200, 0.6924, 0.7600, 0.6687]],

        [[0.2261, 0.5406, 0.9931, 0.9643],
         [0.1827, 0.3307, 0.7319, 0.5923],
         [0.2896, 0.1424, 0.4677, 0.0097],
         [0.0022, 0.9708, 0.7438, 0.8431]],

        [[0.7279, 0.0555, 0.4916, 0.6355],
         [0.2736, 0.5593, 0.3090, 0.3270],
         [0.7108, 0.9340, 0.7653, 0.2824],
         [0.6791, 0.8503, 0.8813, 0.9057]]])

In [16]:
i = torch.tensor([1 , 2 , 3 ,9])
i

tensor([1, 2, 3, 9])

In [17]:
i.dtype

torch.int64

In [18]:
j = torch.tensor([[1. , 2 , 3 , 5] , [3 , 4 , 5 , 6.]])
j

tensor([[1., 2., 3., 5.],
        [3., 4., 5., 6.]])

In [19]:
k = torch.tensor([[[1. , 2 , 3 , 5] , [3 , 4 , 5 , 6.] , [6 , 7 , 8 , 9]],
                 [[1. , 2 , 3 , 5] , [3 , 4 , 5 , 6.] , [6 , 7 , 8 , 9]]])
k

tensor([[[1., 2., 3., 5.],
         [3., 4., 5., 6.],
         [6., 7., 8., 9.]],

        [[1., 2., 3., 5.],
         [3., 4., 5., 6.],
         [6., 7., 8., 9.]]])

In [20]:
l = torch.ones(1 , dtype = torch.float16 )
l

tensor([1.], dtype=torch.float16)

In [21]:
m = torch.ones(1 , dtype = torch.double )
m

tensor([1.], dtype=torch.float64)

In [22]:
n = torch.ones(1 , dtype = torch.int16 )
n

tensor([1], dtype=torch.int16)

# Resape a Tensor

In [23]:
a = torch.rand(3 , 4)
a

tensor([[0.2216, 0.2933, 0.9381, 0.2945],
        [0.2542, 0.1951, 0.3392, 0.0027],
        [0.8298, 0.0811, 0.0296, 0.6483]])

In [24]:
b = a.view(6,2)
b

tensor([[0.2216, 0.2933],
        [0.9381, 0.2945],
        [0.2542, 0.1951],
        [0.3392, 0.0027],
        [0.8298, 0.0811],
        [0.0296, 0.6483]])

In [25]:
c = a.reshape(6,2,1)
c

tensor([[[0.2216],
         [0.2933]],

        [[0.9381],
         [0.2945]],

        [[0.2542],
         [0.1951]],

        [[0.3392],
         [0.0027]],

        [[0.8298],
         [0.0811]],

        [[0.0296],
         [0.6483]]])

In [26]:
d = a.reshape(1, 12)
d

tensor([[0.2216, 0.2933, 0.9381, 0.2945, 0.2542, 0.1951, 0.3392, 0.0027, 0.8298,
         0.0811, 0.0296, 0.6483]])

# Convert a Tensor into numpy

In [27]:
a = torch.rand(3 , 4)
a

tensor([[0.1918, 0.1467, 0.1263, 0.1314],
        [0.1067, 0.6157, 0.7536, 0.8535],
        [0.5026, 0.7165, 0.6113, 0.5539]])

In [28]:
type(a)

torch.Tensor

In [29]:
b = a.numpy()
b

array([[0.19180948, 0.1466785 , 0.1263156 , 0.13140035],
       [0.10671067, 0.61572105, 0.75358677, 0.8535302 ],
       [0.5025735 , 0.71651787, 0.6112548 , 0.5539344 ]], dtype=float32)

In [30]:
type(b)

numpy.ndarray

In [31]:
b[0][1] = 1

In [32]:
b

array([[0.19180948, 1.        , 0.1263156 , 0.13140035],
       [0.10671067, 0.61572105, 0.75358677, 0.8535302 ],
       [0.5025735 , 0.71651787, 0.6112548 , 0.5539344 ]], dtype=float32)

In [33]:
a

tensor([[0.1918, 1.0000, 0.1263, 0.1314],
        [0.1067, 0.6157, 0.7536, 0.8535],
        [0.5026, 0.7165, 0.6113, 0.5539]])

In [34]:
a.device

device(type='cpu')

# Convert Numpy into Tensor

In [35]:
import numpy as np

In [36]:
num_a = np.array([1 , 5 , 7 , 9])
num_a

array([1, 5, 7, 9])

In [37]:
type(num_a)

numpy.ndarray

In [38]:
num_a.dtype

dtype('int64')

In [39]:
a = torch.as_tensor(num_a.astype(np.float16))
a

tensor([1., 5., 7., 9.], dtype=torch.float16)

In [40]:
b = torch.tensor(num_a.astype(np.float16))
b

tensor([1., 5., 7., 9.], dtype=torch.float16)

In [41]:
a.type()

'torch.HalfTensor'

In [42]:
b.type()

'torch.HalfTensor'

In [43]:
type(a)

torch.Tensor

In [44]:
num_a

array([1, 5, 7, 9])

In [45]:
c = torch.from_numpy(num_a.astype(np.float32))
c

tensor([1., 5., 7., 9.])

In [46]:
type(c)

torch.Tensor

# Slicing

In [47]:
a = torch.rand(4 , 5)
a

tensor([[0.2650, 0.8719, 0.9806, 0.0919, 0.0573],
        [0.1149, 0.3115, 0.5255, 0.9860, 0.7429],
        [0.6829, 0.6795, 0.2109, 0.4122, 0.7297],
        [0.7614, 0.7800, 0.5752, 0.6243, 0.4865]])

In [48]:
a[: , 2:]

tensor([[0.9806, 0.0919, 0.0573],
        [0.5255, 0.9860, 0.7429],
        [0.2109, 0.4122, 0.7297],
        [0.5752, 0.6243, 0.4865]])

In [49]:
a[2: , :]

tensor([[0.6829, 0.6795, 0.2109, 0.4122, 0.7297],
        [0.7614, 0.7800, 0.5752, 0.6243, 0.4865]])

In [50]:
a[1 : 3 , 3 : 5]

tensor([[0.9860, 0.7429],
        [0.4122, 0.7297]])

# Stack and Concatenate

In [51]:
a = torch.rand(2 , 3)
b = torch.rand(2 , 3)
print(a)
print(b)


tensor([[0.9974, 0.9531, 0.0136],
        [0.5188, 0.4636, 0.1691]])
tensor([[0.6313, 0.5803, 0.9293],
        [0.6195, 0.8043, 0.2038]])


In [52]:
c = torch.stack([a , b] , axis = 0)
c

tensor([[[0.9974, 0.9531, 0.0136],
         [0.5188, 0.4636, 0.1691]],

        [[0.6313, 0.5803, 0.9293],
         [0.6195, 0.8043, 0.2038]]])

In [53]:
d = torch.stack([a , b] , axis = 1)
d

tensor([[[0.9974, 0.9531, 0.0136],
         [0.6313, 0.5803, 0.9293]],

        [[0.5188, 0.4636, 0.1691],
         [0.6195, 0.8043, 0.2038]]])

In [54]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])


In [55]:
e = torch.cat([a , b] , axis = 0)
e

tensor([[0.9974, 0.9531, 0.0136],
        [0.5188, 0.4636, 0.1691],
        [0.6313, 0.5803, 0.9293],
        [0.6195, 0.8043, 0.2038]])

In [56]:
f = torch.cat([a , b] , axis =1)
f

tensor([[0.9974, 0.9531, 0.0136, 0.6313, 0.5803, 0.9293],
        [0.5188, 0.4636, 0.1691, 0.6195, 0.8043, 0.2038]])

In [57]:
print(a.shape)
print(b.shape)
print(e.shape)
print(f.shape)

torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([4, 3])
torch.Size([2, 6])


In [58]:
g = torch.rand(5 , 3)
g

tensor([[0.2707, 0.0838, 0.4084],
        [0.8010, 0.5066, 0.9563],
        [0.9417, 0.6907, 0.0620],
        [0.2762, 0.4983, 0.5471],
        [0.4383, 0.6404, 0.7493]])

In [59]:
h = torch.cat([a , g] , axis = 0)
h

tensor([[0.9974, 0.9531, 0.0136],
        [0.5188, 0.4636, 0.1691],
        [0.2707, 0.0838, 0.4084],
        [0.8010, 0.5066, 0.9563],
        [0.9417, 0.6907, 0.0620],
        [0.2762, 0.4983, 0.5471],
        [0.4383, 0.6404, 0.7493]])

In [60]:
i = torch.cat([b , g] , axis = 0)
i

tensor([[0.6313, 0.5803, 0.9293],
        [0.6195, 0.8043, 0.2038],
        [0.2707, 0.0838, 0.4084],
        [0.8010, 0.5066, 0.9563],
        [0.9417, 0.6907, 0.0620],
        [0.2762, 0.4983, 0.5471],
        [0.4383, 0.6404, 0.7493]])

In [61]:
print(a.shape)
print(b.shape)
print(h.shape)
print(i.shape)

torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([7, 3])
torch.Size([7, 3])


# Copy a Tensor

In [62]:
a = torch.rand(2 , 4 , 1)
a

tensor([[[0.4178],
         [0.7196],
         [0.9821],
         [0.2196]],

        [[0.5327],
         [0.4855],
         [0.0938],
         [0.7471]]])

In [63]:
b = torch.rand(2 , 4 , 1)
b

tensor([[[0.5940],
         [0.4755],
         [0.8611],
         [0.8088]],

        [[0.0249],
         [0.7556],
         [0.3490],
         [0.5792]]])

In [64]:
c = a

In [65]:
c

tensor([[[0.4178],
         [0.7196],
         [0.9821],
         [0.2196]],

        [[0.5327],
         [0.4855],
         [0.0938],
         [0.7471]]])

In [66]:
c[1,1:][1:3] = 1

In [67]:
c

tensor([[[0.4178],
         [0.7196],
         [0.9821],
         [0.2196]],

        [[0.5327],
         [0.4855],
         [1.0000],
         [1.0000]]])

In [68]:
a

tensor([[[0.4178],
         [0.7196],
         [0.9821],
         [0.2196]],

        [[0.5327],
         [0.4855],
         [1.0000],
         [1.0000]]])

# Clone

In [69]:
d = b.clone()

In [70]:
d[1,1:][1:3] = 1

In [71]:
d

tensor([[[0.5940],
         [0.4755],
         [0.8611],
         [0.8088]],

        [[0.0249],
         [0.7556],
         [1.0000],
         [1.0000]]])

In [72]:
b

tensor([[[0.5940],
         [0.4755],
         [0.8611],
         [0.8088]],

        [[0.0249],
         [0.7556],
         [0.3490],
         [0.5792]]])

# Basic Maths Operations

In [73]:
a = torch.ones(2 , 3)
b = torch.ones(2 , 3)

In [74]:
c = torch.add(a , b)
c

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [75]:
d = torch.ones(2 , 5)
e = torch.ones(2 , 5)

In [76]:
d.add_(e)
d

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])

In [77]:
c = torch.sub(a , b)
c

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [78]:
f = torch.mul(a , b)
f

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [79]:
a.device

device(type='cpu')

In [80]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [81]:
device

'cpu'

# Linear Regression

1- Data Prepare

2- Model Design

3- Optimizer and loss

4- Training Loop

    - Forward pass
    
    - loss compute
    
    - backward pass
    
    - weights update
    
    - set weights to zero
    
5- save model weights

6- plot

In [82]:
x = torch.tensor([[1.] , [2.] , [3.] , [4.]] , dtype = torch.float32)
y = torch.tensor([[2.] , [4.] , [6.] , [8.]] , dtype = torch.float32)

In [83]:
w = torch.tensor(0.0 ,requires_grad = True, dtype = torch.float32)
w

tensor(0., requires_grad=True)

In [84]:
import torch.nn as nn

In [85]:
def forward(x):
    return w*x

In [86]:
loss = nn.MSELoss()
learning_rate = 0.01
optimizer = torch.optim.SGD([w] , learning_rate )

In [87]:
num_epochs = 10
for epoch in range(num_epochs):
    y_pred = forward(x)
    loss_true = loss(y_pred , y)

    loss_true.backward()

    optimizer.step()
    optimizer.zero_grad()

    print(f'epoch {epoch} , loss = {loss_true}')


epoch 0 , loss = 30.0
epoch 1 , loss = 21.674999237060547
epoch 2 , loss = 15.660187721252441
epoch 3 , loss = 11.314486503601074
epoch 4 , loss = 8.17471694946289
epoch 5 , loss = 5.9062323570251465
epoch 6 , loss = 4.2672529220581055
epoch 7 , loss = 3.083089828491211
epoch 8 , loss = 2.227532148361206
epoch 9 , loss = 1.609391689300537


In [88]:
z = torch.tensor([[1.] , [2.] , [3.] , [4.]] , dtype = torch.float32)
u = torch.tensor([[2.] , [4.] , [6.] , [8.]] , dtype = torch.float32)

In [89]:
n_samples , n_features = x.shape

In [90]:
input_size = n_features
output_size = 1

In [91]:
model = nn.Linear(input_size , output_size)

In [92]:
loss = nn.MSELoss()
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters() , learning_rate )

In [93]:
num_epochs = 10
for epoch in range(num_epochs):
    y_pred = model(x)
    loss_true = loss(y_pred , y)

    loss_true.backward()

    optimizer.step()
    optimizer.zero_grad()

    print(f'epoch {epoch} , loss = {loss_true}')


epoch 0 , loss = 33.80213165283203
epoch 1 , loss = 23.46192741394043
epoch 2 , loss = 16.287033081054688
epoch 3 , loss = 11.30848503112793
epoch 4 , loss = 7.853930473327637
epoch 5 , loss = 5.456846237182617
epoch 6 , loss = 3.7935171127319336
epoch 7 , loss = 2.63932466506958
epoch 8 , loss = 1.8384133577346802
epoch 9 , loss = 1.2826361656188965


# Linear Regression  

In [94]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [95]:
x_numpy , y_numpy = make_regression(n_samples = 100 , n_features =1 )

In [96]:
train_x , test_x , train_y , test_y = train_test_split(x_numpy , y_numpy , test_size= 0.1 , random_state = 42)

In [97]:
tensor_x = torch.tensor(train_x , dtype = torch.float32)
tensor_test_x = torch.tensor(test_x , dtype = torch.float32)
tensor_y = torch.tensor(train_y , dtype = torch.float32)
tensor_test_y = torch.tensor(test_y , dtype = torch.float32)

In [98]:
n_samples , n_features = tensor_x.shape

In [99]:
tensor_y = tensor_y.view(tensor_y.shape[0],1)

In [100]:
type(tensor_x)

torch.Tensor

# Custom model

In [101]:
class linearregression(nn.Module):

    def __init__(self , input_size , output_size):
        super(linearregression , self).__init__()
        self.linear = nn.Linear(input_size , output_size)

    def forward(self , x):
        output =  self.linear(x)
        return output 


model = linearregression(n_features , output_size  = 1)

In [102]:
loss = nn.MSELoss()
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters() , learning_rate )

In [103]:
num_epochs = 10
for epoch in range(num_epochs):
    y_pred = model(tensor_x)
    loss_true = loss(y_pred , tensor_y)

    loss_true.backward()

    optimizer.step()
    optimizer.zero_grad()

    print(f'epoch {epoch+1} , loss = {loss_true.item()}')


epoch 1 , loss = 8070.74462890625
epoch 2 , loss = 7706.009765625
epoch 3 , loss = 7357.759765625
epoch 4 , loss = 7025.2470703125
epoch 5 , loss = 6707.76171875
epoch 6 , loss = 6404.62353515625
epoch 7 , loss = 6115.185546875
epoch 8 , loss = 5838.82763671875
epoch 9 , loss = 5574.95849609375
epoch 10 , loss = 5323.01513671875


# Custom data Loader

In [104]:
import torchvision
import math
from torch.utils.data import DataLoader , Dataset , random_split


In [111]:
class Wine(Dataset):

    def __init__(self):

        dataset_wine =  np.loadtxt('/kaggle/input/for-pytorch/wine.csv' , delimiter = ',' , skiprows = 1 , dtype = np.float32)
        self.x = torch.from_numpy(dataset_wine[: , 1:])
        self.y = torch.from_numpy(dataset_wine[: , 0]).long()-1
        self.n_samples = dataset_wine.shape[0] 

        self.x = (self.x - self.x.mean(dim = 0)) / self.x.std(dim = 0)

    def __getitem__(self , index):
        return self.x[index] , self.y[index]

    def __len__(self):
        return self.n_samples

dataset = Wine()

train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size

train_dataset , test_dataset = random_split(dataset , [train_size , test_size ])
         
train_loader = DataLoader(dataset = train_dataset , batch_size = 4 , shuffle = True)
test_loader = DataLoader(dataset = test_dataset , batch_size = 4 , shuffle = False)
    

In [112]:
dataiter = iter(train_loader)
data = next(dataiter)
features , labels = data
print(features , labels)

tensor([[ 1.1571, -0.5428, -0.3518, -0.6273,  0.5782,  0.9345,  1.5125, -0.3363,
          0.8545,  1.6572,  0.7112,  0.6878,  1.6294],
        [ 0.1963,  0.0212,  1.1062, -0.2680,  0.0881,  0.8067,  1.2121, -0.4970,
          2.1300,  0.2683,  0.3174,  0.7864,  1.3912],
        [-0.7152, -0.6502, -0.6434,  0.8998,  0.5782, -0.4715,  0.0608, -0.1756,
          0.0334, -1.2932,  0.4487,  0.4906, -1.2762],
        [-1.0355, -0.6502, -0.2060,  0.9897, -0.6821, -0.8231, -0.3397,  0.5476,
         -0.0540, -1.1250,  1.6299, -0.4953, -0.7999]]) tensor([0, 0, 1, 1])


In [113]:
epochs = 20
total_samples = len(dataset)
n_iteration = math.ceil(total_samples / 4)
print(n_iteration)

45


In [117]:
class logisticregression(nn.Module):

    def __init__(self , input_size , output_size):
        super(logisticregression , self).__init__()
        self.linear = nn.Linear(input_size , output_size)

    def forward(self , x):
        output =  self.linear(x)
        return output 


model = logisticregression(input_size = 13 , output_size  = 3)

In [118]:
loss = nn.CrossEntropyLoss()
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters() , learning_rate)

In [119]:
num_epochs = 20
for epoch in range(num_epochs):
    for i , (inputs , labels) in enumerate(train_loader):
        
        y_pred = model(inputs)
        loss_true = loss(y_pred , labels)
    
        loss_true.backward()
    
        optimizer.step()
        optimizer.zero_grad()

    if epoch % 1 == 0:

        print(f'epoch {epoch+1} , loss = {loss_true.item()}')


epoch 1 , loss = 1.2114794254302979
epoch 2 , loss = 0.3444978594779968
epoch 3 , loss = 0.21479785442352295
epoch 4 , loss = 0.3044612407684326
epoch 5 , loss = 0.5902491211891174
epoch 6 , loss = 0.1649474799633026
epoch 7 , loss = 0.40917956829071045
epoch 8 , loss = 0.13998281955718994
epoch 9 , loss = 0.0698872059583664
epoch 10 , loss = 0.2209712415933609
epoch 11 , loss = 0.04454587399959564
epoch 12 , loss = 0.1948825865983963
epoch 13 , loss = 0.08482571691274643
epoch 14 , loss = 0.06745993345975876
epoch 15 , loss = 0.17298948764801025
epoch 16 , loss = 0.025702865794301033
epoch 17 , loss = 0.12775763869285583
epoch 18 , loss = 0.08411040902137756
epoch 19 , loss = 0.17125681042671204
epoch 20 , loss = 0.14504536986351013


In [123]:
total_correct_test = 0
total_test_samples = 0
with torch.no_grad():
    for inputs , labels in test_loader:
        y_pred_test = torch.argmax(model(inputs) , dim = 1)
        total_correct_test += (y_pred_test == labels).sum().item()
        total_test_samples += labels.size(0)

    test_accuracy = total_correct_test / total_test_samples

#print(f"Train Accuracy: {train_accuracy:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f}")

Test Accuracy: 0.9722
